bitmap_conv.exe ../data/impsbru.plt cross_frames/cube_0000s_0000_A-Open.png -o ../data/cross_frames/cube_a_open.bm -mo ../data/cross_frames/cube_a_open.msk -mc #FF00FF
bitmap_conv.exe ../data/impsbru.plt cross_frames/cube_0000s_0001_A-Closed.png -o ../data/cross_frames/cube_a_closed.bm -mo ../data/cross_frames/cube_a_closed.msk -mc #FF00FF
bitmap_conv.exe ../data/impsbru.plt cross_frames/cube_0000s_0002_A-Final.png -o ../data/cross_frames/cube_a_final.bm -mo ../data/cross_frames/cube_a_final.msk -mc #FF00FF
bitmap_conv.exe ../data/impsbru.plt cross_frames/cube_0000s_0003_C-Open.png -o ../data/cross_frames/cube_c_open.bm -mo ../data/cross_frames/cube_c_open.msk -mc #FF00FF
bitmap_conv.exe ../data/impsbru.plt cross_frames/cube_0000s_0004_C-Closed.png -o ../data/cross_frames/cube_c_closed.bm -mo ../data/cross_frames/cube_c_closed.msk -mc #FF00FF
bitmap_conv.exe ../data/impsbru.plt cross_frames/cube_0000s_0005_C-Final.png -o ../data/cross_frames/cube_c_final.bm -mo ../data/cross_frames/cube_c_final.msk -mc #FF00FF
bitmap_conv.exe ../data/impsbru.plt cross_frames/cube_0000s_0006_E-Open.png -o ../data/cross_frames/cube_e_open.bm -mo ../data/cross_frames/cube_e_open.msk -mc #FF00FF
bitmap_conv.exe ../data/impsbru.plt cross_frames/cube_0000s_0007_E-Closed.png -o ../data/cross_frames/cube_e_closed.bm -mo ../data/cross_frames/cube_e_closed.msk -mc #FF00FF
bitmap_conv.exe ../data/impsbru.plt cross_frames/cube_0000s_0008_E-Final.png -o ../data/cross_frames/cube_e_final.bm -mo ../data/cross_frames/cube_e_final.msk -mc #FF00FF
bitmap_conv.exe ../data/impsbru.plt cross_frames/cube_0000s_0009_B-Open.png -o ../data/cross_frames/cube_b_open.bm -mo ../data/cross_frames/cube_b_open.msk -mc #FF00FF
bitmap_conv.exe ../data/impsbru.plt cross_frames/cube_0000s_0010_B-Closed.png -o ../data/cross_frames/cube_b_closed.bm -mo ../data/cross_frames/cube_b_closed.msk -mc #FF00FF
bitmap_conv.exe ../data/impsbru.plt cross_frames/cube_0000s_0011_D-Open.png -o ../data/cross_frames/cube_d_open.bm -mo ../data/cross_frames/cube_d_open.msk -mc #FF00FF
bitmap_conv.exe ../data/impsbru.plt cross_frames/cube_0000s_0012_D-Closed.png -o ../data/cross_frames/cube_d_closed.bm -mo ../data/cross_frames/cube_d_closed.msk -mc #FF00FF
bitmap_conv.exe ../data/impsbru.plt cross_frames/cube_0000s_0013_F-Open.png -o ../data/cross_frames/cube_f_open.bm -mo ../data/cross_frames/cube_f_open.msk -mc #FF00FF
bitmap_conv.exe ../data/impsbru.plt cross_frames/cube_0000s_0014_F-Closed.png -o ../data/cross_frames/cube_f_closed.bm -mo ../data/cross_frames/cube_f_closed.msk -mc #FF00FF
bitmap_conv.exe ../data/impsbru.plt cross_frames/cube_0000s_0015_Center.png -o ../data/cross_frames/cube_center.bm -mo ../data/cross_frames/cube_center.msk -mc #FF00FF
bitmap_conv.exe ../data/impsbru.plt cross_frames/cube_0000s_0016_Cleanup.png -o ../data/cross_frames/cleanup.bm -mo ../data/cross_frames/cleanup.msk -mc #FF00FF