bitmap_conv.exe ../data/impsbru.plt cross_frames/cross_0000s_0000_A-Final.png -o ../data/cross_frames/a_final.bm -mo ../data/cross_frames/a_final.msk -mc #FF00FF
bitmap_conv.exe ../data/impsbru.plt cross_frames/cross_0000s_0001_C-Final.png -o ../data/cross_frames/c_final.bm -mo ../data/cross_frames/c_final.msk -mc #FF00FF
bitmap_conv.exe ../data/impsbru.plt cross_frames/cross_0000s_0002_E-Final.png -o ../data/cross_frames/e_final.bm -mo ../data/cross_frames/e_final.msk -mc #FF00FF
bitmap_conv.exe ../data/impsbru.plt cross_frames/cross_0001_Cursor.png -o ../data/cross_frames/cursor.bm -mo ../data/cross_frames/cursor.msk -mc #FF00FF
bitmap_conv.exe ../data/impsbru.plt cross_frames/cross_0001s_0000_A.png -o ../data/cross_frames/a.bm -mo ../data/cross_frames/a.msk -mc #FF00FF
bitmap_conv.exe ../data/impsbru.plt cross_frames/cross_0001s_0001_C.png -o ../data/cross_frames/c.bm -mo ../data/cross_frames/c.msk -mc #FF00FF
bitmap_conv.exe ../data/impsbru.plt cross_frames/cross_0001s_0002_E.png -o ../data/cross_frames/e.bm -mo ../data/cross_frames/e.msk -mc #FF00FF
bitmap_conv.exe ../data/impsbru.plt cross_frames/cross_0001s_0003_B.png -o ../data/cross_frames/b.bm -mo ../data/cross_frames/b.msk -mc #FF00FF
bitmap_conv.exe ../data/impsbru.plt cross_frames/cross_0001s_0004_D.png -o ../data/cross_frames/d.bm -mo ../data/cross_frames/d.msk -mc #FF00FF
bitmap_conv.exe ../data/impsbru.plt cross_frames/cross_0001s_0005_F.png -o ../data/cross_frames/f.bm -mo ../data/cross_frames/f.msk -mc #FF00FF
bitmap_conv.exe ../data/impsbru.plt cross_frames/cross_0001s_0006_Center.png -o ../data/cross_frames/center.bm -mo ../data/cross_frames/center.msk -mc #FF00FF
bitmap_conv.exe ../data/impsbru.plt cross_frames/cross_0000_Cleanup.png -o ../data/cross_frames/cleanup.bm -mo ../data/cross_frames/cleanup.msk -mc #FF00FF