#ifndef GUARD_IMPSBRU_CONFIG_H
#define GUARD_IMPSBRU_CONFIG_H

#define CROSS_SIDE_A 0
#define CROSS_SIDE_B 1
#define CROSS_SIDE_C 2
#define CROSS_SIDE_D 3
#define CROSS_SIDE_E 4
#define CROSS_SIDE_F 5
#define CROSS_SIDE_COUNT 6

#define CROSS_SIDE_MODE_OPEN 1
#define CROSS_SIDE_MODE_CLOSED 2
#define CROSS_SIDE_MODE_FINAL 3
#define CROSS_SIDE_MODE_COUNT 3
#define CROSS_SIDE_MODE_BYTES 2

#define ATLAS_COUNT (1 + (CROSS_SIDE_COUNT * CROSS_SIDE_MODE_COUNT))

#define CROSS_WIDTH 64
#define CROSS_HEIGHT 64
#define CROSS_X_SHIFT 50
#define CROSS_Y_SHIFT 50
#define CROSS_EVEN_Y_SHIFT 25

#define CROSS_SIDE_A_OPEN (CROSS_SIDE_MODE_OPEN << (CROSS_SIDE_MODE_BYTES * CROSS_SIDE_A))
#define CROSS_SIDE_B_OPEN (CROSS_SIDE_MODE_OPEN << (CROSS_SIDE_MODE_BYTES * CROSS_SIDE_B))
#define CROSS_SIDE_C_OPEN (CROSS_SIDE_MODE_OPEN << (CROSS_SIDE_MODE_BYTES * CROSS_SIDE_C))
#define CROSS_SIDE_D_OPEN (CROSS_SIDE_MODE_OPEN << (CROSS_SIDE_MODE_BYTES * CROSS_SIDE_D))
#define CROSS_SIDE_E_OPEN (CROSS_SIDE_MODE_OPEN << (CROSS_SIDE_MODE_BYTES * CROSS_SIDE_E))
#define CROSS_SIDE_F_OPEN (CROSS_SIDE_MODE_OPEN << (CROSS_SIDE_MODE_BYTES * CROSS_SIDE_F))

#define CROSS_SIDE_A_CLOSED (CROSS_SIDE_MODE_CLOSED << (CROSS_SIDE_MODE_BYTES * CROSS_SIDE_A))
#define CROSS_SIDE_B_CLOSED (CROSS_SIDE_MODE_CLOSED << (CROSS_SIDE_MODE_BYTES * CROSS_SIDE_B))
#define CROSS_SIDE_C_CLOSED (CROSS_SIDE_MODE_CLOSED << (CROSS_SIDE_MODE_BYTES * CROSS_SIDE_C))
#define CROSS_SIDE_D_CLOSED (CROSS_SIDE_MODE_CLOSED << (CROSS_SIDE_MODE_BYTES * CROSS_SIDE_D))
#define CROSS_SIDE_E_CLOSED (CROSS_SIDE_MODE_CLOSED << (CROSS_SIDE_MODE_BYTES * CROSS_SIDE_E))
#define CROSS_SIDE_F_CLOSED (CROSS_SIDE_MODE_CLOSED << (CROSS_SIDE_MODE_BYTES * CROSS_SIDE_F))

#define CROSS_SIDE_A_FINAL (CROSS_SIDE_MODE_FINAL << (CROSS_SIDE_MODE_BYTES * CROSS_SIDE_A))
#define CROSS_SIDE_B_FINAL (CROSS_SIDE_MODE_FINAL << (CROSS_SIDE_MODE_BYTES * CROSS_SIDE_B))
#define CROSS_SIDE_C_FINAL (CROSS_SIDE_MODE_FINAL << (CROSS_SIDE_MODE_BYTES * CROSS_SIDE_C))
#define CROSS_SIDE_D_FINAL (CROSS_SIDE_MODE_FINAL << (CROSS_SIDE_MODE_BYTES * CROSS_SIDE_D))
#define CROSS_SIDE_E_FINAL (CROSS_SIDE_MODE_FINAL << (CROSS_SIDE_MODE_BYTES * CROSS_SIDE_E))
#define CROSS_SIDE_F_FINAL (CROSS_SIDE_MODE_FINAL << (CROSS_SIDE_MODE_BYTES * CROSS_SIDE_F))

#endif